# https://docs.docker.com/compose/compose-file/
services:
  web:
    build:
      context: .
    ports:
      - "3000:80"
    volumes:
      - ./nginx/development/config.js:/usr/share/nginx/html/config.js
    env_file:
      - ./nginx/development/.env.development